version: '3'

services:
  eventuate-db:
    container_name: eventuate
    networks:
      - api
    image: eventuateio/eventuate-postgres:latest
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate
      POSTGRES_DB: eventuate
    ports:
      - "5432:5432"

  event-db:
    container_name: event
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    ports:
      - "5433:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.4
    networks:
      - api
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_SERVERS: "zookeeper:22888:23888"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: confluentinc/cp-kafka:5.0.4
    container_name: kafka
    networks:
      - api
    ports:
      - '9092:9092'
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  cdcservice:
    image: eventuateio/eventuate-cdc-service:0.13.0.BUILD-SNAPSHOT
    networks:
      - api
    ports:
      - "8099:8080"
    depends_on:
      - eventuate-db
      - kafka
      - zookeeper
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_READER_READER1_TYPE: postgres-wal
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:postgresql://eventuate-db/eventuate
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: eventuate
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: eventuate
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/common
      EVENTUATE_CDC_READER_READER1_OFFSETSTORAGETOPICNAME: db.history.common
      EVENTUATE_CDC_READER_READER1_OUTBOXID: "1"
networks:
  api:
